# Generated by Django 4.1 on 2023-08-16 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('passport', models.ImageField(upload_to='')),
                ('business_name', models.CharField(max_length=100)),
                ('bussiness_address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField(null=True)),
                ('home_address', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('guarantors_name', models.CharField(max_length=100)),
                ('guarantors_phone', models.IntegerField()),
                ('guarantors_address', models.CharField(max_length=100)),
                ('goccupation', models.CharField(max_length=100, null=True)),
                ('gstate', models.CharField(max_length=100, null=True)),
                ('branch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('due', models.BooleanField()),
                ('expected_payment_days', models.IntegerField(default=25)),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customers')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.branch')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.state')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.state'),
        ),
    ]
