# Generated by Django 4.1 on 2023-08-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalmanagers', '0001_initial'),
        ('managers', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='card_number',
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
        migrations.AddField(
            model_name='state',
            name='general_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generalmanagers.generalmanager'),
        ),
        migrations.DeleteModel(
            name='GeneralManager',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
