# Generated by Django 4.1 on 2023-08-16 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('generalmanagers', '0001_initial'),
        ('administration', '0002_remove_manager_branch_remove_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
        migrations.AlterField(
            model_name='state',
            name='general_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generalmanagers.generalmanager'),
        ),
    ]
