# Generated by Django 4.1 on 2023-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_branch_manager_alter_state_general_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='card_number',
            field=models.IntegerField(default=944332445665),
            preserve_default=False,
        ),
    ]
