# Generated by Django 4.1 on 2023-08-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_customers_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_paid',
        ),
        migrations.CreateModel(
            name='ApplyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customers')),
            ],
        ),
    ]
