# Generated by Django 4.1 on 2023-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_loan_amount_paid_applyloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
