# Generated by Django 4.1 on 2023-08-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_loanapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.customers'),
        ),
        migrations.DeleteModel(
            name='ApplyLoan',
        ),
    ]
