# Generated by Django 4.1 on 2023-08-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_loan_loanee_delete_applyloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customers'),
        ),
    ]
