# Generated by Django 4.1 on 2023-09-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_loan_loanee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customers')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='paid',
            name='paymentday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.paymentday'),
        ),
    ]
