# Generated by Django 4.1 on 2023-09-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_paid_paymentday_delete_payment_paid_paymentday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid',
            name='customer',
        ),
    ]
