# Generated by Django 4.1 on 2023-09-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_paymentday_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentday',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
